color0 #334a50
color1 #ffb4ab
color2 #72daa5
color3 #90d5ae
color4 #83d3e3
color5 #72daa5
color6 #90d5ae
color7 #d8e5e8
color8 #7c959b
color9 #ffb4ab
color10 #72daa5
color11 #90d5ae
color12 #83d3e3
color13 #72daa5
color14 #90d5ae
color15 #d8e5e8

cursor                #d8e5e8
cursor_text_color     #091518
background            #091518
foreground            #d8e5e8
selection_foreground  #b1cbd1
selection_background  #334a50
active_border_color   #72daa5
inactive_border_color #334a50
url_color             #72daa5

active_tab_foreground   #003822
active_tab_background   #72daa5
inactive_tab_foreground #b1cbd1
inactive_tab_background #334a50
cursor_trail_color      #b1cbd1
