color0 #334a50
color1 #ffb4ab
color2 #d8e5e8
color3 #d8e5e8
color4 #83d3e3
color5 #d8e5e8
color6 #d8e5e8
color7 #d8e5e8
color8 #7c959b
color9 #ffb4ab
color10 #d8e5e8
color11 #d8e5e8
color12 #83d3e3
color13 #d8e5e8
color14 #d8e5e8
color15 #d8e5e8

cursor                #d8e5e8
cursor_text_color     #091518
background            #091518
foreground            #d8e5e8
selection_foreground  #b1cbd1
selection_background  #334a50
active_border_color   #d8e5e8
inactive_border_color #334a50
url_color             #d8e5e8

active_tab_foreground   #003822
active_tab_background   #d8e5e8
inactive_tab_foreground #b1cbd1
inactive_tab_background #334a50
cursor_trail_color      #b1cbd1